name: Dynamic Tap Validation

on:
  push:
    branches:
      - gcl27
      - maxima
      - acl2
      - fricas
      - axiom
      - hol88
  pull_request:

jobs:
  core:
    if: github.ref_name == 'acl2'
    strategy:
      matrix:
        include:
          - os: macos-26
            arch: arm64
          - os: macos-26-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew Framework
        uses: Homebrew/actions/setup-homebrew@main

      - name: Build ACL2
        env:
          HOMEBREW_ACL2_BUILD: "core"
          HOMEBREW_ACL2_OCF: "acl2-core-${{ matrix.arch }}.tar.gz"
        run: |
          brew audit --formula "cammgh/math/acl2-gcl" --online || echo "Audit failure, continuing"
          brew install --formula --verbose --build-from-source "cammgh/math/acl2-gcl"
          find $(brew --prefix) -name "acl2-core-${{ matrix.arch }}.tar.gz" -exec cp {} . \;

      - name: Upload Core State Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acl2-core-state-${{ matrix.arch }}
          path: acl2-core-${{ matrix.arch }}.tar.gz

      - name: Open Debug SSH Session on Failure
        if: failure()
        uses: owenthereal/action-upterm@v1
        with:
          upterm-command: /bin/bash --noprofile --norc


  books:
    needs: core
    if: github.ref_name == 'acl2'
    strategy:
      matrix:
        include:
          - os: macos-26
            arch: arm64
          - os: macos-26-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew Framework
        uses: Homebrew/actions/setup-homebrew@main

      - name: Download Core State Artifact
        uses: actions/download-artifact@v4
        with:
          name: acl2-core-state-${{ matrix.arch }}

      - name: Verify Book Regression Subset
        env:
          HOMEBREW_ACL2_BUILD: "books"
          HOMEBREW_ACL2_ICF: "${{ github.workspace }}/acl2-core-${{ matrix.arch }}.tar.gz"
          HOMEBREW_ACL2_OCF: "acl2-books-${{ matrix.arch }}-1.tar.gz"
        run: |
          brew install --formula --verbose --build-from-source "cammgh/math/acl2-gcl"
          find $(brew --prefix) -name "acl2-books-${{ matrix.arch }}-1.tar.gz" -exec cp {} . \;

      - name: Upload Verified Books Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acl2-books-state-${{ matrix.arch }}-1
          path: acl2-books-${{ matrix.arch }}-1.tar.gz

      - name: Open Debug SSH Session on Failure
        if: failure()
        uses: owenthereal/action-upterm@v1
        with:
          upterm-command: /bin/bash --noprofile --norc

  books1:
    needs: books
    if: github.ref_name == 'acl2'
    strategy:
      matrix:
        include:
          - os: macos-26
            arch: arm64
          - os: macos-26-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew Framework
        uses: Homebrew/actions/setup-homebrew@main

      - name: Download Core State Artifact
        uses: actions/download-artifact@v4
        with:
          name: acl2-books-state-${{ matrix.arch }}-1

      - name: Verify Book Regression Subset
        env:
          HOMEBREW_ACL2_BUILD: "books"
          HOMEBREW_ACL2_ICF: "${{github.workspace}}/acl2-books-${{ matrix.arch }}-1.tar.gz"
          HOMEBREW_ACL2_OCF: "acl2-books-${{ matrix.arch }}-2.tar.gz"
        run: |
          brew install --formula --verbose --build-from-source "cammgh/math/acl2-gcl"
          find $(brew --prefix) -name "acl2-books-${{ matrix.arch }}-2.tar.gz" -exec cp {} . \;

      - name: Upload Verified Books Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acl2-books-state-${{ matrix.arch }}-2
          path: acl2-books-${{ matrix.arch }}-2.tar.gz

      - name: Open Debug SSH Session on Failure
        if: failure()
        uses: owenthereal/action-upterm@v1
        with:
          upterm-command: /bin/bash --noprofile --norc

  books2:
    needs: books1
    if: github.ref_name == 'acl2'
    strategy:
      matrix:
        include:
          - os: macos-26
            arch: arm64
          - os: macos-26-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew Framework
        uses: Homebrew/actions/setup-homebrew@main

      - name: Download Core State Artifact
        uses: actions/download-artifact@v4
        with:
          name: acl2-books-state-${{ matrix.arch }}-2

      - name: Verify Book Regression Subset
        env:
          HOMEBREW_ACL2_BUILD: "books"
          HOMEBREW_ACL2_ICF: "${{github.workspace}}/acl2-books-${{ matrix.arch }}-2.tar.gz"
          HOMEBREW_ACL2_OCF: "acl2-books-${{ matrix.arch }}-3.tar.gz"
        run: |
          brew install --formula --verbose --build-from-source "cammgh/math/acl2-gcl"
          find $(brew --prefix) -name "acl2-books-${{ matrix.arch }}-3.tar.gz" -exec cp {} . \;

      - name: Upload Verified Books Artifact
        uses: actions/upload-artifact@v4
        with:
          name: acl2-books-state-${{ matrix.arch }}-3
          path: acl2-books-${{ matrix.arch }}-3.tar.gz

      - name: Open Debug SSH Session on Failure
        if: failure()
        uses: owenthereal/action-upterm@v1
        with:
          upterm-command: /bin/bash --noprofile --norc


  build:
    needs: books2
    if: always() && ((github.ref_name == 'acl2' && needs.books2.result == 'success')||(github.ref_name != 'acl2'))
    strategy:
      matrix:
        include:
          - os: macos-26
            arch: arm64
          - os: macos-26-intel
            arch: x86_64

    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew Framework
        uses: Homebrew/actions/setup-homebrew@main

      - name: Extract Dynamic Version Tag
        id: get_version
        run: |
          FN="${{ github.ref_name }}"
          if [ "$FN" != "gcl27" ] ; then FN="$FN-gcl"; fi
          echo "fn=${FN}" >> $GITHUB_OUTPUT
          VERSION=$(grep -E '^[[:space:]]*version[[:space:]]+' Formula/$FN.rb | awk -F'"' '{print $2}')
          echo "Extracted Version: $VERSION"
          echo "tag_name=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Compile
        if: github.ref_name != 'acl2'
        run: |
          FN="${{ steps.get_version.outputs.fn }}"
          brew audit --formula "cammgh/math/$FN" --online || echo "Audit warning, proceeding"
          brew install --formula --verbose --build-bottle "cammgh/math/$FN"
          brew test "cammgh/math/$FN"

      - name: Download Final Books Artifacts
        if: github.ref_name == 'acl2'
        uses: actions/download-artifact@v4
        with:
          name: acl2-books-state-${{ matrix.arch }}-3

      - name: Reassemble Workspace and Install
        if: github.ref_name == 'acl2'
        env:
          HOMEBREW_ACL2_BUILD: "install"
          HOMEBREW_ACL2_ICF: "${{ github.workspace }}/acl2-books-${{ matrix.arch }}-3.tar.gz"
        run: |
          brew install --formula --verbose --build-bottle "cammgh/math/acl2-gcl"
          brew test "cammgh/math/acl2-gcl"

      - name: Bottle
        run: |
          TAG="${{ steps.get_version.outputs.tag_name }}"
          brew bottle --json --root-url="https://github.com/cammgh/homebrew-math/releases/download/${TAG}" "cammgh/math/${{ steps.get_version.outputs.fn }}"
          FN="${{ steps.get_version.outputs.fn }}"
          sed -i '' "s,${FN}--,${FN}-,g" *--*json
          for i in *--*; do mv $i $(echo $i | sed 's,--,-,1'); done

      - name: Deploy Bottles to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          name: "Precompiled Binaries (${{ steps.get_version.outputs.tag_name }})"
          body: "Automated binary asset engine distributions"
          draft: false
          prerelease: false
          files: |
            ${{ steps.get_version.outputs.fn }}*.bottle.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JSON Metadata
        uses: actions/upload-artifact@v4
        with:
          name: bottle-json-${{ matrix.os }}
          path: "*.bottle.json"

      - name: Open Debug SSH Session on Failure
        if: failure()
        uses: owenthereal/action-upterm@v1
        with:
          upterm-command: /bin/bash --noprofile --norc

  merge_push:
    needs: build
    if: always() && !failure() && !cancelled()
    runs-on: macos-26
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Homebrew Framework
        uses: Homebrew/actions/setup-homebrew@main

      - name: Download All JSON Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: bottle-json-*
          merge-multiple: true # Dumps all json files into the same folder

      - name: Merge Bottle Hashes and Update Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          FN="${{ github.ref_name }}"
          if [ "$FN" != "gcl27" ] ; then FN="$FN-gcl"; fi
          brew bottle --merge --write ${FN}*.bottle.json
          git push origin HEAD:${{ github.ref_name }}

      - name: Open Debug SSH Session on Failure
        if: failure()
        uses: owenthereal/action-upterm@v1
        with:
          upterm-command: /bin/bash --noprofile --norc
